-- Generated from the legacy Notta Decants MySQL export.
-- This imports products only; users, coupons and reviews are intentionally excluded.
begin;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Sauvage', 'sauvage-8', 'Dior', 'Uno de los masculinos más vendidos del mundo, fresco y potente. Aromático fresco | Bergamota de Calabria, Pimienta | Lavanda, Geranio Sichuan | Ambroxan, Cedro', 'Frasco completo', 15000, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa2fa2f46efc5.28794461.jpg', 'EDT', 5, true, true, 8) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Oud Wood', 'oud-wood-10', 'Tom Ford', 'Amaderado de lujo, suave y sofisticado, sin la crudeza del oud puro. Amaderado | Oud, Palo de rosa | Sándalo, Vetiver | Ámbar, Cardamomo', 'Frasco completo', 20000, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5f32b6f6f33.12606950.webp', 'EDP', 2, true, true, 10) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Tobacco Vanille', 'tobacco-vanille-11', 'Tom Ford', 'Cálido, dulce y envolvente. Un clásico moderno de nicho. Oriental gourmand | Tabaco, Especias | Cacao, Tonka | Vainilla, Madera', 'Frasco completo', 18000, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa2dcba648ec3.51674635.webp', 'EDP', 2, true, false, 11) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Hawas Ice', 'hawas-ice-14', 'Rasasi', 'Explosión fresca y helada con base dulce sumamente duradera. Cítrico acuático | Manzana, Limón italiano, Bergamota de Sicilia | Ciruela, Azahar, Cardamomo | Almizcle, Ámbar, Musgo de roble', 'Frasco completo', 115920, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa2312a211f54.82731687.webp', 'EDP', 100, true, true, 14) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Hawas Tropical', 'hawas-tropical-15', 'Rasasi', 'Perfil frutal y exótico de alta proyección para climas cálidos. Frutal aromático | Mango, Maracuyá, Notas cítricas | Notas marinas, Jazmín | Sándalo, Almizcle blanco, Ámbar', 'Frasco completo', 135240, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5f4c68194b3.76867934.jpeg', 'EDP', 100, true, false, 15) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Hawas Malibu', 'hawas-malibu-16', 'Rasasi', 'Fragancia vibrante inspirada en la costa, limpia y versátil. Acuático amaderado | Mandarina, Agua marina | Salvia, Geranio | Vetiver, Cedro, Ámbar', 'Frasco completo', 121716, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa33ec114b232.27114028.webp', 'EDP', 100, true, false, 16) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Liquid Brun Limited Edition', 'liquid-brun-limited-edition-17', 'Lattafa', 'Extrait cálido, gourmand y especiado con una vainilla adictiva. Inspirado en Althaïr (Parfums de Marly). Oriental amaderado | Canela, Bergamota, Cardamomo, Flor de azahar | Vainilla bourbon, Élémi | Praliné, Ambroxan, Almizcle, Madera de Gaiac', 'Frasco completo', 148120, 'ARS', 1, null, 'EDP', 150, false, true, 17) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('9 AM Dive', '9-am-dive-19', 'Lattafa', 'Fresco, versátil y todoterreno con salida chispeante y fondo limpio. Inspirado en Bleu de Chanel / Y EDP. Aromático acuático | Menta, Limón, Manzana verde, Grosellas negras | Cedro, Incienso, Pimienta | Jazmín, Pachulí, Sándalo', 'Frasco completo', 104328, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa33f29b23d73.58830588.jpeg', 'EDP', 100, true, false, 19) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Your Touch Leather', 'your-touch-leather-20', 'Lattafa', 'Cuero ahumado y sofisticado con el contraste dulce de la frambuesa. Inspirado en Tom Ford Tuscan Leather. Cuero especiado | Frambuesa, Azafrán, Tomillo | Olibano, Jazmín | Cuero, Gamuza, Ámbar, Notas amaderadas', 'Frasco completo', 77280, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa33fa1691395.88605828.jpeg', 'EDP', 100, true, false, 20) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Stallion 53 Mandora', 'stallion-53-mandora-21', 'Lattafa', 'Cítrico aromático elegante presentado con minitalla de 20ml para viaje. Cítrico amaderado | Mandarina italiana, Naranja amarga | Pimienta rosa, Azahar | Almizcle, Pachulí, Cedro', 'Frasco completo', 61180, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa3412c4c8976.87610312.jpeg', 'EDP', 100, true, false, 21) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Stallion 53 Uomo Intense', 'stallion-53-uomo-intense-22', 'Lattafa', 'Fragancia empolvada, dulce y seductora dominada por el iris y el cuero. Inspirado en Valentino Uomo Intense. Cuero oriental | Mandarina, Salvia | Iris, Haba tonka | Cuero negro, Vainilla', 'Frasco completo', 80500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa340df050c18.10328846.webp', 'EDP', 100, true, false, 22) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('9PM Night Out', '9pm-night-out-23', 'Lattafa', 'Extrait nocturno juvenil de gran estela y fijación dulce y envolvente. Inspirado en Ultra Male (Jean Paul Gaultier). Oriental especiado | Manzana silvestre, Bergamota, Canela | Lavanda, Flor de azahar | Vainilla negra, Ámbar gris, Haba tonka', 'Frasco completo', 161000, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5f4776f8093.32885218.jpeg', 'EDP', 100, true, true, 23) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Odyssey Mega', 'odyssey-mega-24', 'Armaf', 'Aroma azul moderno, fresco y metálico de proyección duradera. Inspirado en Y EDP (YSL). Aromático amaderado | Jengibre, Bergamota, Naranja | Enebro, Salvia, Geranio | Vetiver, Cedro, Haba tonka, Almizcle', 'Frasco completo', 96600, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa34194d825b2.85099260.jpeg', 'EDP', 100, true, false, 24) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Hercules', 'hercules-25', 'Lattafa', 'Tabaco dulce avainillado y cálido ideal para épocas frías. Inspirado en Herod (Parfums de Marly). Amaderado especiado | Canela, Pimienta negra | Hojas de tabaco, Incienso, Osmanto | Vainilla, Cedro, Almizcle, Vetiver', 'Frasco completo', 61824, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa2fba0dc4e48.72876883.jpg', 'EDP', 100, true, false, 25) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Dark Door Sport', 'dark-door-sport-26', 'Lattafa', 'Cítrico picante deportivo con un fondo resinoso elegante. Inspirado en Dior Homme Sport. Amaderado cítrico | Limón, Bergamota, Aldehídos | Pimienta rosa, Elemí | Incienso, Notas amaderadas, Ámbar', 'Frasco completo', 77280, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa2fc80ab2072.44583269.webp', 'EDP', 100, true, false, 26) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Taureau de Combat', 'taureau-de-combat-27', 'Lattafa', 'Lanzamiento de Lattafa Pride con una presencia imponente de maderas y tabaco. Inspirado en Centaurus (Creed). Ámbar especiado | Cardamomo, Canela, Benjuí, Ámbar | Tabaco, Cachemira, Jazmín, Heliotropo | Pachulí, Vainilla, Haba tonka', 'Frasco completo', 139104, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa34091cf6ab4.32851373.webp', 'EDP', 100, true, true, 27) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Italia Rayhaan', 'italia-rayhaan-28', 'Lattafa', 'Aroma fresco estilo colonia italiana mediterránea con excelente fijación. Cítrico aromático | Bergamota, Mandarina, Neroli | Azahar, Lavanda, Romero | Almizcle, Ámbar, Cedro', 'Frasco completo', 144900, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa2fdf2cf2df9.17789034.jpg', 'EDP', 100, true, false, 28) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Erba Pura', 'erba-pura-29', 'Tom Ford', 'Ícono de la perfumería nicho mundial con estela avasallante y frutas almizcladas. Oriental frutal | Naranja siciliana, Bergamota de Calabria, Limón | Cesta de frutas mediterráneas | Almizcle blanco, Vainilla de Madagascar, Ámbar', 'Frasco completo', 450800, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa2f9ae0d3f18.09657479.jpg', 'EDP', 100, true, true, 29) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Tom Ford Myrrhe Mystere', 'tom-ford-myrrhe-mystere-31', 'Tom Ford', 'Fragancia de la Private Blend oscura, mística y resinosa de altísimo lujo. Ámbar amaderado | Mirra, Esencia de mirra | Sándalo, Jazmín | Vainilla ultra, Ámbar ahumado', 'Frasco completo', 547400, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa3421b229c68.86875344.webp', 'EDP', 50, true, true, 31) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Bharara Bleu', 'decant-bharara-bleu-32', 'Bharara', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 12500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a4fb23ede5.32802079.webp', 'EDP', 5, true, false, 32) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Lattafa Hayaati', 'decant-lattafa-hayaati-33', 'Lattafa', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 7500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a54f55a029.76071749.webp', 'EDP', 5, true, false, 33) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Niche Emarati Hayaam', 'decant-niche-emarati-hayaam-34', 'Niche Emarati', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 7500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a56689b292.82862865.webp', 'EDP', 5, true, false, 34) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Lattafa Asad Bourbon', 'decant-lattafa-asad-bourbon-35', 'Lattafa', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 8500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a58a7c8766.65083372.webp', 'EDP', 5, true, false, 35) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Dolce & Gabbana Light Blue', 'decant-dolce-gabbana-light-blue-36', 'Dolce & Gabbana', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 13500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a59cdc5b52.92217892.webp', 'EDP', 5, true, false, 36) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Viktor & Rolf Spicebomb Dark Leather', 'decant-viktor-rolf-spicebomb-dark-leather-37', 'Viktor & Rolf', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 16000, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a5bf603ac1.22693892.webp', 'EDP', 5, true, false, 37) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Armaf Hunter Jungle', 'decant-armaf-hunter-jungle-38', 'Armaf', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 6900, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a5dc734b22.46516982.webp', 'EDP', 5, true, false, 38) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Armaf Hunter Killer', 'decant-armaf-hunter-killer-39', 'Armaf', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 6900, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a5e7837a42.84284646.webp', 'EDP', 5, true, false, 39) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Sharaf The Club', 'decant-sharaf-the-club-40', 'Sharaf', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 8500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a60e717dd6.22502959.webp', 'EDP', 5, true, false, 40) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Sharaf Blend', 'decant-sharaf-blend-41', 'Sharaf', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 8500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a61be7fc57.16599737.webp', 'EDP', 5, true, false, 41) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Lattafa Confidential Platinum', 'decant-lattafa-confidential-platinum-42', 'Lattafa', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 7500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a62c482b47.36236394.webp', 'EDP', 5, true, false, 42) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Lattafa Confidential Private Gold', 'decant-lattafa-confidential-private-gold-43', 'Lattafa', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 7500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a6387748d3.02855604.webp', 'EDP', 5, true, false, 43) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Tom Ford Costa Azzurra', 'decant-tom-ford-costa-azzurra-44', 'Tom Ford', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 30000, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a644c4d6c0.34608303.webp', 'EDP', 5, true, false, 44) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Lattafa Gift Of Universe', 'decant-lattafa-gift-of-universe-45', 'Lattafa', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 9000, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a65408f9e1.40237085.webp', 'EDP', 5, true, false, 45) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Rasasi Hawas Tropical', 'decant-rasasi-hawas-tropical-46', 'Rasasi', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 9000, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a665867dc6.44373649.webp', 'EDP', 5, true, false, 46) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Rasasi Hawas Malibu', 'decant-rasasi-hawas-malibu-47', 'Rasasi', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 9000, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a67237c9e9.63938932.webp', 'EDP', 5, true, false, 47) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Armaf Club De Nuit Iconic', 'decant-armaf-club-de-nuit-iconic-48', 'Armaf', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 9000, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a68417f890.48408165.webp', 'EDP', 5, true, false, 48) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Armaf Club De Nuit Precieux I', 'decant-armaf-club-de-nuit-precieux-i-49', 'Armaf', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 16500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a693bec7e7.68818083.webp', 'EDP', 5, true, false, 49) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Odyssey Limoni', 'decant-odyssey-limoni-50', 'Armaf', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 7500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a6a0286a14.98274961.webp', 'EDP', 5, true, false, 50) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Emporio Armani Stronger With You Intensely', 'decant-emporio-armani-stronger-with-you-intensely-51', 'Emporio Armani', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 17500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a6aa4a6e85.49164414.webp', 'EDP', 5, true, false, 51) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Lattafa Atlas', 'decant-lattafa-atlas-52', 'Lattafa', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 12500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a6b6dfc0b6.17774890.webp', 'EDP', 5, true, false, 52) on conflict (slug) do nothing;
insert into public.products (name, slug, brand, description, category, price, currency, stock, image_url, concentration, size_ml, is_published, is_featured, sort_order)
values ('Decant Lattafa Asad Zanzibar', 'decant-lattafa-asad-zanzibar-53', 'Lattafa', 'Decant disponible en presentaciones de 5 ml y 10 ml.', 'Decant', 7500, 'ARS', 1, 'https://ufkckpsgngfcimgugsni.supabase.co/storage/v1/object/public/product-images/legacy/prod_6aa5a6c1810241.18285901.webp', 'EDP', 5, true, false, 53) on conflict (slug) do nothing;
commit;
